INSERT INTO `jian_category` VALUES('1','1','content','1','0','0','0','1','1,2,3,4,5','网站介绍','','','','','about','/html/about/','0','0','array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','1','0','0','wangzhanjieshao','');
INSERT INTO `jian_category` VALUES('2','1','content','1','0','1','0,1','0','2','关于我们','','','','about/','aboutus','/html/about/aboutus/','0','0','array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'关于我们\',
  \'meta_keywords\' => \'关于我们\',
  \'meta_description\' => \'关于我们\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','1','1','0','guanyuwomen','');
INSERT INTO `jian_category` VALUES('3','1','content','1','0','1','0,1','0','3','联系方式','','','','about/','contactus','/html/about/contactus/','0','0','array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'联系方式\',
  \'meta_keywords\' => \'联系方式\',
  \'meta_description\' => \'联系方式\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','2','1','0','lianxifangshi','');
INSERT INTO `jian_category` VALUES('4','1','content','1','0','1','0,1','0','4','版权声明','','','','about/','copyright','http://www.jianrenxiao.com/index.php?m=content&c=index&a=lists&catid=4','0','0','array (
  \'ishtml\' => \'0\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'版权声明\',
  \'meta_keywords\' => \'版权声明\',
  \'meta_description\' => \'版权声明\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','3','1','0','banquanshengming','');
INSERT INTO `jian_category` VALUES('5','1','content','1','0','1','0,1','0','5','招聘信息','','','','about/','hr','/html/about/hr/','0','0','array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','4','1','0','zhaopinxinxi','');
INSERT INTO `jian_category` VALUES('6','1','content','0','1','0','0','0','6','国内','','','','','guonei','http://www.jianrenxiao.com/index.php?m=content&c=index&a=lists&catid=6','4','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'jrx\',
  \'category_template\' => \'\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','1','0','0','guonei','');
INSERT INTO `jian_category` VALUES('7','1','content','0','2','0','0','0','7','下载','','','','','down','http://www.jianrenxiao.com/index.php?m=content&c=index&a=lists&catid=7','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'jrx\',
  \'category_template\' => \'\',
  \'list_template\' => \'\',
  \'show_template\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','2','0','0','xiazai','');
INSERT INTO `jian_category` VALUES('8','1','content','0','3','0','0','0','8','图片','','','','','pps','http://www.jianrenxiao.com/index.php?m=content&c=index&a=lists&catid=8','2','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'jrx\',
  \'category_template\' => \'\',
  \'list_template\' => \'\',
  \'show_template\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','3','0','0','tupian','');
INSERT INTO `jian_category` VALUES('9','1','content','0','1','0','0','0','9','首页','','','','','sy','','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'jrx\',
  \'category_template\' => \'\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','9','1','0','shouye','');
INSERT INTO `jian_category` VALUES('10','1','content','0','1','0','0','0','10','贱人笑话','','','','','jrxh','','5','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'jrx\',
  \'category_template\' => \'\',
  \'list_template\' => \'list_xh\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','10','1','0','jianrenxiaohua','');
INSERT INTO `jian_category` VALUES('11','1','content','0','1','0','0','0','11','贱人内涵','','','','','jrnh','','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'jrx\',
  \'category_template\' => \'\',
  \'list_template\' => \'list_nh\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','11','1','0','jianrenneihan','');
INSERT INTO `jian_category` VALUES('12','1','content','0','1','0','0','0','12','贱人爆图','','','','','jrbt','','6','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'jrx\',
  \'category_template\' => \'\',
  \'list_template\' => \'list_bt\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','12','1','0','jianrenbaotu','');
INSERT INTO `jian_category` VALUES('13','1','content','0','1','0','0','0','13','贱人电台','','','','','jrdt','','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'jrx\',
  \'category_template\' => \'\',
  \'list_template\' => \'list_dt\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','13','1','0','jianrendiantai','');
